#file: noinspection ComposeUnknownKeys
name: eclipsephp-frontend-panel
services:
  appserver:
    type: php:custom
    xdebug: "debug,develop,coverage"
    via: cli
    overrides:
      image: slimdeluxe/php:8.3-v1.3
tooling:
  php:
    service: appserver
  composer:
    service: appserver
  test:
    service: appserver
    description: Run tests
    cmd: "composer test"
  format:
    service: appserver
    description: Fix code style issues
    cmd: "composer format"
  testbench:
    service: appserver
    description: Run testbench CLI
    cmd: "vendor/bin/testbench"
